### PR TITLE
Added new function to remove device groups.

### PR DESCRIPTION
**Pull request by svenborer**
Ciao, I have added a function to remove device groups. Also updated the manifest to a new patch version if that is ok for you. If you want me to add more checks (Checking whether the ID exists), or adding a tree path as a string as an input, just let me know, so I can implement that as well. We already use the function on our environment, so its tested. Feel free to merge it into your module. Best & thanks for your work, Sven.

### CODE REVIEW

**Comment by wetling23** [comment]
Great, I will have a look.

**Comment by wetling23** [comment]
I would like to make the cmdlet support the two query params available in this API endpoint, but I ran into some odd behavior. I have opened a case with LogicMonitor and will add my bit and then add this to the module, once the LM ticket gets resolved.

**Comment by svenborer** [comment]
Thanks! There is also an encoding issue we have. Chars like Æ, Ø or Å are not supported. I already have an easy fix, I will add another pull request for that later.

**Comment by wetling23** [comment]
> Thanks! There is also an encoding issue we have. Chars like Æ, Ø or Å are not supported. I already have an easy fix, I will add another pull request for that later.

Yeah, that's probably true for the entire module. When you submit it, I will review your workaround and (if feasible), work it into the rest of module's commands. 

An update on the LM support ticket: 

`So - deleteChildren is definitely bugged - we tested it multiple ways and it's failing to respect the children groups in every sample. So I've created a DEV-TS for this problem.`

**Comment by wetling23** [comment]
I am closing the PR because I think I may have messed it up. I have the code locally, and will push it to the master branch, separate from this PR.

**Pull request closed without merging**
